export const USER_REQUEST = "USER_REQUEST";
export const USER_FAILURE = "USER_FAILURE";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const PATCH_USER_SUCCESS = "PATCH_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
